backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "_data/noticias"
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Resumo", name: "description", widget: "string"}
      - {label: "Corpo da Notícia", name: "body", widget: "markdown"}
